In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
import csv

txt_file = r"data_banknote_authentication.txt"
csv_file = r"data.csv"

in_txt = csv.reader(open(txt_file, "rt"), delimiter = ',')
out_csv = csv.writer(open(csv_file, 'wt'))

out_csv.writerows(in_txt)

In [3]:

cols = "variance skewness curtosis entropy class".split()
cols

['variance', 'skewness', 'curtosis', 'entropy', 'class']

In [4]:
df = pd.read_csv("data_banknote_authentication.txt",names=cols)

In [5]:
df.head(10)

variance  skewness  curtosis  entropy  class
0   3.62160    8.6661  -2.80730 -0.44699      0
1   4.54590    8.1674  -2.45860 -1.46210      0
2   3.86600   -2.6383   1.92420  0.10645      0
3   3.45660    9.5228  -4.01120 -3.59440      0
4   0.32924   -4.4552   4.57180 -0.98880      0
5   4.36840    9.6718  -3.96060 -3.16250      0
6   3.59120    3.0129   0.72888  0.56421      0
7   2.09220   -6.8100   8.46360 -0.60216      0
8   3.20320    5.7588  -0.75345 -0.61251      0
9   1.53560    9.1772  -2.27180 -0.73535      0

In [6]:
from sklearn.preprocessing import StandardScaler

In [7]:
scaler = StandardScaler()

In [8]:
scaler.fit(df.drop(['class'],axis=1))

StandardScaler(copy=True, with_mean=True, with_std=True)

In [9]:
features = scaler.transform(df.drop('class',axis=1))

In [10]:
features[0]

array([ 1.12180565,  1.14945512, -0.97597007,  0.35456135])

In [11]:
x = features
y = df['class']

In [12]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split

In [13]:
model = KNeighborsClassifier(n_neighbors=1)

In [14]:
x_train,x_test,y_train,y_test = train_test_split(x,y)

In [15]:
model.fit(x_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=1, p=2,
           weights='uniform')

In [16]:
model.score(x_test,y_test) * 100

100.0

In [17]:
from sklearn.metrics import confusion_matrix

In [18]:
pred = model.predict(x_test)

confusion_matrix(y_test,pred)

array([[189,   0],
       [  0, 154]], dtype=int64)

In [19]:
from sklearn.metrics import classification_report

In [20]:
print(classification_report(y_test,pred))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00       189
          1       1.00      1.00      1.00       154

avg / total       1.00      1.00      1.00       343



In [21]:
from sklearn.externals import joblib

In [22]:
joblib.dump(model,"note_predictor.pkl")

['note_predictor.pkl']

In [23]:
ne_model = joblib.load('note_predictor.pkl')

In [24]:
ne_model.predict(x_test)

array([0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1,
       1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0,